-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 11:08:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diceGame
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diceGame` ;

-- -----------------------------------------------------
-- Schema diceGame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diceGame` DEFAULT CHARACTER SET utf8 ;
USE `diceGame` ;

-- -----------------------------------------------------
-- Table `diceGame`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diceGame`.`player` ;

CREATE TABLE IF NOT EXISTS `diceGame`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `reg` DATETIME NULL,
  `status` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diceGame`.`dice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diceGame`.`dice` ;

CREATE TABLE IF NOT EXISTS `diceGame`.`dice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value1` INT NULL,
  `value2` INT NULL,
  `status` TINYINT NULL,
  `reg` DATETIME NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`id`, `player_id`),
  INDEX `fk_dice_player_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_dice_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `diceGame`.`player` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
